fix: version

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,126 +1,99 @@
-name: Release Advanced Auto Clicker
+name: Continuous Delivery
 
 on:
   push:
     branches:
-      - master
+      - main
+
+# default: least privileged permissions across all jobs
+permissions:
+  contents: read
 
 jobs:
-  bump-version:
-    name: Determine next version
-    runs-on: ubuntu-latest
-    outputs:
-      new_version: ${{ steps.semantic_release.outputs.new_version }}
-    steps:
-      - uses: actions/checkout@v3
-
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.10'
-
-      - name: Install python-semantic-release
-        run: pip install python-semantic-release
-
-      - name: Run python-semantic-release to publish and get version
-        id: semantic_release
-        run: |
-            semantic-release publish
-            version=$(semantic-release version)
-            echo "new_version=$version" >> $GITHUB_OUTPUT
-        env:
-            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
- 
-  build-linux:
-    needs: bump-version
-    runs-on: ubuntu-latest
-    env:
-      VERSION: ${{ needs.bump-version.outputs.new_version }}
-    steps:
-      - uses: actions/checkout@v3
-
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.x'
-
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install pyinstaller customtkinter pyautogui pynput pillow keyboard
-
-      - name: Build Linux executable
-        run: |
-          chmod +x ./build-linux.sh
-          ./build-linux.sh "$VERSION"
-
-      - name: Upload Linux executable
-        uses: actions/upload-artifact@v3
-        with:
-          name: AdvancedAutoClicker-linux-$VERSION
-          path: ./dist/AdvancedAutoClicker
-
-  build-windows:
-    needs: bump-version
-    runs-on: windows-latest
-    env:
-      VERSION: ${{ needs.bump-version.outputs.new_version }}
-    steps:
-      - uses: actions/checkout@v3
-
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.x'
-
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          pip install pyinstaller customtkinter pyautogui pynput pillow keyboard
-
-      - name: Build Windows executable
-        run: |
-          call .\install_deps.bat
-          python build_exe.py %VERSION%
-
-      - name: Upload Windows executable
-        uses: actions/upload-artifact@v3
-        with:
-          name: AdvancedAutoClicker-windows-${{ env.VERSION }}
-          path: .\dist\AdvancedAutoClicker.exe
-
   release:
-    needs: [build-linux, build-windows]
     runs-on: ubuntu-latest
+    concurrency:
+      group: ${{ github.workflow }}-release-${{ github.ref_name }}
+      cancel-in-progress: false
+
+    permissions:
+      contents: write
+
     steps:
-      - uses: actions/checkout@v3
-
-      - name: Create GitHub Release
-        id: create_release
-        uses: softprops/action-gh-release@v1
+      # Note: We checkout the repository at the branch that triggered the workflow
+      # with the entire history to ensure to match PSR's release branch detection
+      # and history evaluation.
+      # However, we forcefully reset the branch to the workflow sha because it is
+      # possible that the branch was updated while the workflow was running. This
+      # prevents accidentally releasing un-evaluated changes.
+      - name: Setup | Checkout Repository on Release Branch
+        uses: actions/checkout@v4
         with:
-          tag_name: ${{ needs.bump-version.outputs.new_version }}
-          name: Advanced Auto Clicker ${{ needs.bump-version.outputs.new_version }}
-          body: |
-            Automated release generated by GitHub Actions.
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          ref: ${{ github.ref_name }}
+          fetch-depth: 0
 
-      - name: Upload Linux executable to release
-        uses: softprops/action-gh-release@v1
-        with:
-          tag_name: ${{ needs.bump-version.outputs.new_version }}
-          name: AdvancedAutoClicker-linux-${{ needs.bump-version.outputs.new_version }}
-          asset_path: ./dist/AdvancedAutoClicker
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Setup | Force release branch to be at workflow sha
+        run: |
+          git reset --hard ${{ github.sha }}
 
-      - name: Upload Windows executable to release
-        uses: softprops/action-gh-release@v1
+      - name: Evaluate | Verify upstream has NOT changed
+        # Last chance to abort before causing an error as another PR/push was applied to
+        # the upstream branch while this workflow was running. This is important
+        # because we are committing a version change (--commit). You may omit this step
+        # if you have 'commit: false' in your configuration.
+        #
+        # You may consider moving this to a repo script and call it from this step instead
+        # of writing it in-line.
+        shell: bash
+        run: |
+          set +o pipefail
+
+          UPSTREAM_BRANCH_NAME="$(git status -sb | head -n 1 | cut -d' ' -f2 | grep -E '\.{3}' | cut -d'.' -f4)"
+          printf '%s\n' "Upstream branch name: $UPSTREAM_BRANCH_NAME"
+
+          set -o pipefail
+
+          if [ -z "$UPSTREAM_BRANCH_NAME" ]; then
+              printf >&2 '%s\n' "::error::Unable to determine upstream branch name!"
+              exit 1
+          fi
+
+          git fetch "${UPSTREAM_BRANCH_NAME%%/*}"
+
+          if ! UPSTREAM_SHA="$(git rev-parse "$UPSTREAM_BRANCH_NAME")"; then
+              printf >&2 '%s\n' "::error::Unable to determine upstream branch sha!"
+              exit 1
+          fi
+
+          HEAD_SHA="$(git rev-parse HEAD)"
+
+          if [ "$HEAD_SHA" != "$UPSTREAM_SHA" ]; then
+              printf >&2 '%s\n' "[HEAD SHA] $HEAD_SHA != $UPSTREAM_SHA [UPSTREAM SHA]"
+              printf >&2 '%s\n' "::error::Upstream has changed, aborting release..."
+              exit 1
+          fi
+
+          printf '%s\n' "Verified upstream branch has not changed, continuing with release..."
+
+      - name: Action | Semantic Version Release
+        id: release
+        # Adjust tag with desired version if applicable.
+        uses: python-semantic-release/python-semantic-release@v10.2.0
         with:
-          tag_name: ${{ needs.bump-version.outputs.new_version }}
-          name: AdvancedAutoClicker-windows-${{ needs.bump-version.outputs.new_version }}.exe
-          asset_path: .\dist\AdvancedAutoClicker.exe
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          git_committer_name: "github-actions"
+          git_committer_email: "actions@users.noreply.github.com"
+
+      - name: Publish | Upload to GitHub Release Assets
+        uses: python-semantic-release/publish-action@v10.2.0
+        if: steps.release.outputs.released == 'true'
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
+          tag: ${{ steps.release.outputs.tag }}
+
+      - name: Upload | Distribution Artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: distribution-artifacts
+          path: dist
+          if-no-files-found: error
